#ifndef __S2_JAD_TXRXCOMMS_V2_10_H__
#define __S2_JAD_TXRXCOMMS_V2_10_H__



/*
* STRUCTURE S2_JAD_TxRxComms_v2_10___9
*/
#define _9__S2_JAD_TxRxComms_v2_10__10_STRING_MAX_LEN 100
#define _9__S2_JAD_TxRxComms_v2_10__11_STRING_MAX_LEN 100
#define _9__S2_JAD_TxRxComms_v2_10__13_STRING_MAX_LEN 100
START_STRUCTURE_DEFINITION( S2_JAD_TxRxComms_v2_10, _9 )
{
   CREATE_STRING_STRUCT( S2_JAD_TxRxComms_v2_10, _9___10, _9__S2_JAD_TxRxComms_v2_10__10_STRING_MAX_LEN );
   DECLARE_STRING_STRUCT( S2_JAD_TxRxComms_v2_10, _9___10 );
   CREATE_STRING_STRUCT( S2_JAD_TxRxComms_v2_10, _9___11, _9__S2_JAD_TxRxComms_v2_10__11_STRING_MAX_LEN );
   DECLARE_STRING_STRUCT( S2_JAD_TxRxComms_v2_10, _9___11 );
   CREATE_STRING_STRUCT( S2_JAD_TxRxComms_v2_10, _9___13, _9__S2_JAD_TxRxComms_v2_10__13_STRING_MAX_LEN );
   DECLARE_STRING_STRUCT( S2_JAD_TxRxComms_v2_10, _9___13 );
   unsigned short _9___12;
   unsigned short _9___14;
};


/*
* Constructor and Destructor
*/
int S2_JAD_TxRxComms_v2_10__9_Constructor ( START_STRUCTURE_DEFINITION( S2_JAD_TxRxComms_v2_10, _9 ) * me, int nVerbose );
int S2_JAD_TxRxComms_v2_10__9_Destructor ( START_STRUCTURE_DEFINITION( S2_JAD_TxRxComms_v2_10, _9 ) * me, int nVerbose );

/*
* DIGITAL_INPUT
*/
#define __S2_JAD_TxRxComms_v2_10_SOIP_ENABLE_DIG_INPUT 0
#define __S2_JAD_TxRxComms_v2_10_START_MODULE_DIG_INPUT 1
#define __S2_JAD_TxRxComms_v2_10_DEBUG_DIG_INPUT 2


/*
* ANALOG_INPUT
*/
#define __S2_JAD_TxRxComms_v2_10_AUDIO_DELAY_ANALOG_INPUT 3
#define __S2_JAD_TxRxComms_v2_10_TEAR_ADJUST_ANALOG_INPUT 4

#define __S2_JAD_TxRxComms_v2_10_TX_STRING_INPUT 0
#define __S2_JAD_TxRxComms_v2_10_TX_STRING_MAX_LEN 255
CREATE_STRING_STRUCT( S2_JAD_TxRxComms_v2_10, __TX, __S2_JAD_TxRxComms_v2_10_TX_STRING_MAX_LEN );
#define __S2_JAD_TxRxComms_v2_10_CRESTRON_ID_STRING_INPUT 1
#define __S2_JAD_TxRxComms_v2_10_CRESTRON_ID_STRING_MAX_LEN 100
CREATE_STRING_STRUCT( S2_JAD_TxRxComms_v2_10, __CRESTRON_ID, __S2_JAD_TxRxComms_v2_10_CRESTRON_ID_STRING_MAX_LEN );
#define __S2_JAD_TxRxComms_v2_10_CONSOLE_CMD_STRING_INPUT 2
#define __S2_JAD_TxRxComms_v2_10_CONSOLE_CMD_STRING_MAX_LEN 250
CREATE_STRING_STRUCT( S2_JAD_TxRxComms_v2_10, __CONSOLE_CMD, __S2_JAD_TxRxComms_v2_10_CONSOLE_CMD_STRING_MAX_LEN );



/*
* DIGITAL_OUTPUT
*/


/*
* ANALOG_OUTPUT
*/

#define __S2_JAD_TxRxComms_v2_10_RX_STRING_OUTPUT 0
#define __S2_JAD_TxRxComms_v2_10_VERSION$_STRING_OUTPUT 1


/*
* Direct Socket Variables
*/

#define __S2_JAD_TxRxComms_v2_10_JAP_DEV_TELNET_SOCKET 5
#define __S2_JAD_TxRxComms_v2_10_JAP_DEV_TELNET_STRING_MAX_LEN 65533
START_SOCKET_DEFINITION( S2_JAD_TxRxComms_v2_10, __JAP_DEV_TELNET )
{
   int SocketStatus;
   enum ESplusSocketType eSocketType;
   int SocketID;
   void *SocketPtr;
CREATE_SOCKET_STRING( S2_JAD_TxRxComms_v2_10, SocketRxBuf, __S2_JAD_TxRxComms_v2_10_JAP_DEV_TELNET_STRING_MAX_LEN );
};
#define __S2_JAD_TxRxComms_v2_10_JAP_DEV_CONTROL_SOCKET 6
#define __S2_JAD_TxRxComms_v2_10_JAP_DEV_CONTROL_STRING_MAX_LEN 65533
START_SOCKET_DEFINITION( S2_JAD_TxRxComms_v2_10, __JAP_DEV_CONTROL )
{
   int SocketStatus;
   enum ESplusSocketType eSocketType;
   int SocketID;
   void *SocketPtr;
CREATE_SOCKET_STRING( S2_JAD_TxRxComms_v2_10, SocketRxBuf, __S2_JAD_TxRxComms_v2_10_JAP_DEV_CONTROL_STRING_MAX_LEN );
};



/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* STRING_PARAMETER
*/
#define __S2_JAD_TxRxComms_v2_10_IP_ADDRESS_STRING_PARAMETER 10
#define __S2_JAD_TxRxComms_v2_10_SOIP_MODE_STRING_PARAMETER 11
#define __S2_JAD_TxRxComms_v2_10_BAUD_RATE_STRING_PARAMETER 12
#define __S2_JAD_TxRxComms_v2_10_DATA_BIT_STRING_PARAMETER 13
#define __S2_JAD_TxRxComms_v2_10_PARITY_STRING_PARAMETER 14
#define __S2_JAD_TxRxComms_v2_10_STOP_BIT_STRING_PARAMETER 15
#define __S2_JAD_TxRxComms_v2_10_LICENCE_KEY_STRING_PARAMETER 16
#define __S2_JAD_TxRxComms_v2_10_IP_ADDRESS_PARAM_MAX_LEN 16
CREATE_STRING_STRUCT( S2_JAD_TxRxComms_v2_10, __IP_ADDRESS, __S2_JAD_TxRxComms_v2_10_IP_ADDRESS_PARAM_MAX_LEN );
#define __S2_JAD_TxRxComms_v2_10_SOIP_MODE_PARAM_MAX_LEN 1
CREATE_STRING_STRUCT( S2_JAD_TxRxComms_v2_10, __SOIP_MODE, __S2_JAD_TxRxComms_v2_10_SOIP_MODE_PARAM_MAX_LEN );
#define __S2_JAD_TxRxComms_v2_10_BAUD_RATE_PARAM_MAX_LEN 6
CREATE_STRING_STRUCT( S2_JAD_TxRxComms_v2_10, __BAUD_RATE, __S2_JAD_TxRxComms_v2_10_BAUD_RATE_PARAM_MAX_LEN );
#define __S2_JAD_TxRxComms_v2_10_DATA_BIT_PARAM_MAX_LEN 1
CREATE_STRING_STRUCT( S2_JAD_TxRxComms_v2_10, __DATA_BIT, __S2_JAD_TxRxComms_v2_10_DATA_BIT_PARAM_MAX_LEN );
#define __S2_JAD_TxRxComms_v2_10_PARITY_PARAM_MAX_LEN 4
CREATE_STRING_STRUCT( S2_JAD_TxRxComms_v2_10, __PARITY, __S2_JAD_TxRxComms_v2_10_PARITY_PARAM_MAX_LEN );
#define __S2_JAD_TxRxComms_v2_10_STOP_BIT_PARAM_MAX_LEN 1
CREATE_STRING_STRUCT( S2_JAD_TxRxComms_v2_10, __STOP_BIT, __S2_JAD_TxRxComms_v2_10_STOP_BIT_PARAM_MAX_LEN );
#define __S2_JAD_TxRxComms_v2_10_LICENCE_KEY_PARAM_MAX_LEN 100
CREATE_STRING_STRUCT( S2_JAD_TxRxComms_v2_10, __LICENCE_KEY, __S2_JAD_TxRxComms_v2_10_LICENCE_KEY_PARAM_MAX_LEN );


/*
* INTEGER
*/


/*
* LONG_INTEGER
*/


/*
* SIGNED_INTEGER
*/


/*
* SIGNED_LONG_INTEGER
*/


/*
* STRING
*/
#define __S2_JAD_TxRxComms_v2_10__19_STRING_MAX_LEN 6
CREATE_STRING_STRUCT( S2_JAD_TxRxComms_v2_10, ___19, __S2_JAD_TxRxComms_v2_10__19_STRING_MAX_LEN );
#define __S2_JAD_TxRxComms_v2_10__20_STRING_MAX_LEN 5
CREATE_STRING_STRUCT( S2_JAD_TxRxComms_v2_10, ___20, __S2_JAD_TxRxComms_v2_10__20_STRING_MAX_LEN );
#define __S2_JAD_TxRxComms_v2_10__21_STRING_MAX_LEN 5
CREATE_STRING_STRUCT( S2_JAD_TxRxComms_v2_10, ___21, __S2_JAD_TxRxComms_v2_10__21_STRING_MAX_LEN );
#define __S2_JAD_TxRxComms_v2_10__22_STRING_MAX_LEN 5
CREATE_STRING_STRUCT( S2_JAD_TxRxComms_v2_10, ___22, __S2_JAD_TxRxComms_v2_10__22_STRING_MAX_LEN );
#define __S2_JAD_TxRxComms_v2_10__23_STRING_MAX_LEN 5
CREATE_STRING_STRUCT( S2_JAD_TxRxComms_v2_10, ___23, __S2_JAD_TxRxComms_v2_10__23_STRING_MAX_LEN );
#define __S2_JAD_TxRxComms_v2_10__24_STRING_MAX_LEN 30
CREATE_STRING_STRUCT( S2_JAD_TxRxComms_v2_10, ___24, __S2_JAD_TxRxComms_v2_10__24_STRING_MAX_LEN );
#define __S2_JAD_TxRxComms_v2_10__25_STRING_MAX_LEN 1000
CREATE_STRING_STRUCT( S2_JAD_TxRxComms_v2_10, ___25, __S2_JAD_TxRxComms_v2_10__25_STRING_MAX_LEN );
#define __S2_JAD_TxRxComms_v2_10__31_STRING_MAX_LEN 255
CREATE_STRING_STRUCT( S2_JAD_TxRxComms_v2_10, ___31, __S2_JAD_TxRxComms_v2_10__31_STRING_MAX_LEN );

/*
* STRUCTURE
*/
#define __S2_JAD_TxRxComms_v2_10__16_STRUCT_MAX_LEN 1000
CREATE_STRUCTURE_ARRAY( S2_JAD_TxRxComms_v2_10, ___16, _9, __S2_JAD_TxRxComms_v2_10__16_STRUCT_MAX_LEN );

START_GLOBAL_VAR_STRUCT( S2_JAD_TxRxComms_v2_10 )
{
   void* InstancePtr;
   struct GenericOutputString_s sGenericOutStr;
   unsigned short LastModifiedArrayIndex;

   unsigned short ___18;
   unsigned short ___26;
   unsigned short ___27;
   unsigned short ___28;
   unsigned short ___32;
   unsigned short ___33;
   unsigned short ___34;
   unsigned short ___35;
   unsigned short ___36;
   unsigned short ___37;
   DECLARE_STRING_STRUCT( S2_JAD_TxRxComms_v2_10, ___25 );
   DECLARE_STRING_STRUCT( S2_JAD_TxRxComms_v2_10, ___31 );
   DECLARE_STRING_STRUCT( S2_JAD_TxRxComms_v2_10, __TX );
   DECLARE_STRING_STRUCT( S2_JAD_TxRxComms_v2_10, __CRESTRON_ID );
   DECLARE_STRING_STRUCT( S2_JAD_TxRxComms_v2_10, __CONSOLE_CMD );
   DECLARE_SOCKET( S2_JAD_TxRxComms_v2_10, __JAP_DEV_TELNET );
   DECLARE_SOCKET( S2_JAD_TxRxComms_v2_10, __JAP_DEV_CONTROL );
   DECLARE_STRUCT( S2_JAD_TxRxComms_v2_10, _9, ___15 );
   DECLARE_STRUCT( S2_JAD_TxRxComms_v2_10, _9, ___17 );
   DECLARE_STRUCT_ARRAY( S2_JAD_TxRxComms_v2_10, ___16 );
   DECLARE_STRING_STRUCT( S2_JAD_TxRxComms_v2_10, __IP_ADDRESS );
   DECLARE_STRING_STRUCT( S2_JAD_TxRxComms_v2_10, __SOIP_MODE );
   DECLARE_STRING_STRUCT( S2_JAD_TxRxComms_v2_10, __BAUD_RATE );
   DECLARE_STRING_STRUCT( S2_JAD_TxRxComms_v2_10, __DATA_BIT );
   DECLARE_STRING_STRUCT( S2_JAD_TxRxComms_v2_10, __PARITY );
   DECLARE_STRING_STRUCT( S2_JAD_TxRxComms_v2_10, __STOP_BIT );
   DECLARE_STRING_STRUCT( S2_JAD_TxRxComms_v2_10, __LICENCE_KEY );
};

START_NVRAM_VAR_STRUCT( S2_JAD_TxRxComms_v2_10 )
{
   DECLARE_STRING_STRUCT( S2_JAD_TxRxComms_v2_10, ___19 );
   DECLARE_STRING_STRUCT( S2_JAD_TxRxComms_v2_10, ___20 );
   DECLARE_STRING_STRUCT( S2_JAD_TxRxComms_v2_10, ___21 );
   DECLARE_STRING_STRUCT( S2_JAD_TxRxComms_v2_10, ___22 );
   DECLARE_STRING_STRUCT( S2_JAD_TxRxComms_v2_10, ___23 );
   DECLARE_STRING_STRUCT( S2_JAD_TxRxComms_v2_10, ___24 );
   unsigned short ___29;
   unsigned short ___30;
};

DEFINE_WAITEVENT( S2_JAD_TxRxComms_v2_10, __SPLS_TMPVAR__WAITLABEL_0__ );
DEFINE_WAITEVENT( S2_JAD_TxRxComms_v2_10, __SPLS_TMPVAR__WAITLABEL_1__ );
DEFINE_WAITEVENT( S2_JAD_TxRxComms_v2_10, __SPLS_TMPVAR__WAITLABEL_2__ );
DEFINE_WAITEVENT( S2_JAD_TxRxComms_v2_10, __SPLS_TMPVAR__WAITLABEL_3__ );
DEFINE_WAITEVENT( S2_JAD_TxRxComms_v2_10, __SPLS_TMPVAR__WAITLABEL_4__ );


#endif //__S2_JAD_TXRXCOMMS_V2_10_H__

