#ifndef __S2_JAP_AVSWITCH_POE_CONTROL_V2_08_H__
#define __S2_JAP_AVSWITCH_POE_CONTROL_V2_08_H__




/*
* Constructor and Destructor
*/

/*
* DIGITAL_INPUT
*/

#define __S2_JAP_AVSwitch_POE_Control_V2_08_SWITCH_ONE_ON_DIG_INPUT 0
#define __S2_JAP_AVSwitch_POE_Control_V2_08_SWITCH_ONE_ON_ARRAY_LENGTH 52
#define __S2_JAP_AVSwitch_POE_Control_V2_08_SWITCH_ONE_OFF_DIG_INPUT 52
#define __S2_JAP_AVSwitch_POE_Control_V2_08_SWITCH_ONE_OFF_ARRAY_LENGTH 52
#define __S2_JAP_AVSwitch_POE_Control_V2_08_SWITCH_TWO_ON_DIG_INPUT 104
#define __S2_JAP_AVSwitch_POE_Control_V2_08_SWITCH_TWO_ON_ARRAY_LENGTH 52
#define __S2_JAP_AVSwitch_POE_Control_V2_08_SWITCH_TWO_OFF_DIG_INPUT 156
#define __S2_JAP_AVSwitch_POE_Control_V2_08_SWITCH_TWO_OFF_ARRAY_LENGTH 52
#define __S2_JAP_AVSwitch_POE_Control_V2_08_SWITCH_THREE_ON_DIG_INPUT 208
#define __S2_JAP_AVSwitch_POE_Control_V2_08_SWITCH_THREE_ON_ARRAY_LENGTH 52
#define __S2_JAP_AVSwitch_POE_Control_V2_08_SWITCH_THREE_OFF_DIG_INPUT 260
#define __S2_JAP_AVSwitch_POE_Control_V2_08_SWITCH_THREE_OFF_ARRAY_LENGTH 52
#define __S2_JAP_AVSwitch_POE_Control_V2_08_SWITCH_FOUR_ON_DIG_INPUT 312
#define __S2_JAP_AVSwitch_POE_Control_V2_08_SWITCH_FOUR_ON_ARRAY_LENGTH 52
#define __S2_JAP_AVSwitch_POE_Control_V2_08_SWITCH_FOUR_OFF_DIG_INPUT 364
#define __S2_JAP_AVSwitch_POE_Control_V2_08_SWITCH_FOUR_OFF_ARRAY_LENGTH 52
#define __S2_JAP_AVSwitch_POE_Control_V2_08_SWITCH_FIVE_ON_DIG_INPUT 416
#define __S2_JAP_AVSwitch_POE_Control_V2_08_SWITCH_FIVE_ON_ARRAY_LENGTH 52
#define __S2_JAP_AVSwitch_POE_Control_V2_08_SWITCH_FIVE_OFF_DIG_INPUT 468
#define __S2_JAP_AVSwitch_POE_Control_V2_08_SWITCH_FIVE_OFF_ARRAY_LENGTH 52
#define __S2_JAP_AVSwitch_POE_Control_V2_08_SWITCH_SIX_ON_DIG_INPUT 520
#define __S2_JAP_AVSwitch_POE_Control_V2_08_SWITCH_SIX_ON_ARRAY_LENGTH 52
#define __S2_JAP_AVSwitch_POE_Control_V2_08_SWITCH_SIX_OFF_DIG_INPUT 572
#define __S2_JAP_AVSwitch_POE_Control_V2_08_SWITCH_SIX_OFF_ARRAY_LENGTH 52
#define __S2_JAP_AVSwitch_POE_Control_V2_08_SWITCH_SEVEN_ON_DIG_INPUT 624
#define __S2_JAP_AVSwitch_POE_Control_V2_08_SWITCH_SEVEN_ON_ARRAY_LENGTH 52
#define __S2_JAP_AVSwitch_POE_Control_V2_08_SWITCH_SEVEN_OFF_DIG_INPUT 676
#define __S2_JAP_AVSwitch_POE_Control_V2_08_SWITCH_SEVEN_OFF_ARRAY_LENGTH 52
#define __S2_JAP_AVSwitch_POE_Control_V2_08_SWITCH_EIGHT_ON_DIG_INPUT 728
#define __S2_JAP_AVSwitch_POE_Control_V2_08_SWITCH_EIGHT_ON_ARRAY_LENGTH 52
#define __S2_JAP_AVSwitch_POE_Control_V2_08_SWITCH_EIGHT_OFF_DIG_INPUT 780
#define __S2_JAP_AVSwitch_POE_Control_V2_08_SWITCH_EIGHT_OFF_ARRAY_LENGTH 52

/*
* ANALOG_INPUT
*/




/*
* DIGITAL_OUTPUT
*/


/*
* ANALOG_OUTPUT
*/

#define __S2_JAP_AVSwitch_POE_Control_V2_08_CMD_STRING_OUTPUT 0


/*
* Direct Socket Variables
*/




/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* STRING_PARAMETER
*/


/*
* INTEGER
*/


/*
* LONG_INTEGER
*/


/*
* SIGNED_INTEGER
*/


/*
* SIGNED_LONG_INTEGER
*/


/*
* STRING
*/

/*
* STRUCTURE
*/

START_GLOBAL_VAR_STRUCT( S2_JAP_AVSwitch_POE_Control_V2_08 )
{
   void* InstancePtr;
   struct GenericOutputString_s sGenericOutStr;
   unsigned short LastModifiedArrayIndex;

   DECLARE_IO_ARRAY( __SWITCH_ONE_ON );
   DECLARE_IO_ARRAY( __SWITCH_ONE_OFF );
   DECLARE_IO_ARRAY( __SWITCH_TWO_ON );
   DECLARE_IO_ARRAY( __SWITCH_TWO_OFF );
   DECLARE_IO_ARRAY( __SWITCH_THREE_ON );
   DECLARE_IO_ARRAY( __SWITCH_THREE_OFF );
   DECLARE_IO_ARRAY( __SWITCH_FOUR_ON );
   DECLARE_IO_ARRAY( __SWITCH_FOUR_OFF );
   DECLARE_IO_ARRAY( __SWITCH_FIVE_ON );
   DECLARE_IO_ARRAY( __SWITCH_FIVE_OFF );
   DECLARE_IO_ARRAY( __SWITCH_SIX_ON );
   DECLARE_IO_ARRAY( __SWITCH_SIX_OFF );
   DECLARE_IO_ARRAY( __SWITCH_SEVEN_ON );
   DECLARE_IO_ARRAY( __SWITCH_SEVEN_OFF );
   DECLARE_IO_ARRAY( __SWITCH_EIGHT_ON );
   DECLARE_IO_ARRAY( __SWITCH_EIGHT_OFF );
};

START_NVRAM_VAR_STRUCT( S2_JAP_AVSwitch_POE_Control_V2_08 )
{
};



#endif //__S2_JAP_AVSWITCH_POE_CONTROL_V2_08_H__

